language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pedropilla/sample-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pedropilla/sample-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "sample-docker-react"
  environment: "SampleDockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-322025820964"
  bucket_path: "sample-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY