language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pedropilla/sample-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pedropilla/sample-docker-react npm run test